###get all
GET http://localhost:3001/users

###get by id
GET http://localhost:3001/users/66fc92046d29b4cb57f018cd

###
POST http://localhost:3001/users HTTP/1.1
content-Type:  application/json

{
    "firstName" : "Karlo",
    "lastName" : "Nole",
    "email" : "karlo.nole@gmail.com",
    "favoriteColor" : "blue",
    "birthday" : "september 11th"
}

###
PUT http://localhost:3001/users/66fc92046d29b4cb57f018cd
Content-Type: application/json

{
    "firstName" : "Karlo",
    "lastName" : "Nole",
    "email" : "karlo.nole29@gmail.com",
    "favoriteColor" : "blue",
    "birthday" : "september 11th"
}

###
DELETE http://localhost:3001/users/6704b8f6bb9e57a1c5e9a2b3